README.md
- Points people to the rather hard to find ES6 supported features
=> docs(readme): Links to closure-compiler ES6 support wiki

package-lock.json, package.json, src/import-dependency-template.js, src/index.js, src/runtime.js
The hash value calculation was incorrect. Refactored so that late-loaded chunk paths are now correctly calculated.
Fixes #2
=> Calculate the correct hash for late-loaded chunks

package-lock.json, package.json
All necessary changes have landed back into the main compiler distribution and have made it into a release. Switches the plugin to use the main build of the compiler instead of a custom one.
=> Switch to the official release of the compiler

package-lock.json, package.json
=> fix: remove unused deps and devDeps

.eslintignore, demo/mixed-modules/.gitignore, demo/mixed-modules/README.md, demo/mixed-modules/package-lock.json, demo/mixed-modules/package.json, demo/mixed-modules/public/index.html, demo/mixed-modules/src/app.js, demo/mixed-modules/src/lib/esModule.js, demo/mixed-modules/src/lib/googModule.js, demo/mixed-modules/src/lib/googRequire.js, demo/mixed-modules/webpack.config.js
Fixes https://github.com/koba04/closure-webpack-example/issues/1
This demo is based on the repository but I've added a compiler flags option.
=> chore: add demo/mixed-modules

package-lock.json, package.json
The schema folder was missing from the npm package. Add it.
Fixes #58
=> Add the schema folder to the npm package

demo/mixed-modules/package-lock.json, demo/mixed-modules/package.json, demo/mixed-modules/src/app.js, demo/mixed-modules/src/lib/esModule.js, demo/mixed-modules/webpack.config.js, package-lock.json, src/goog-loader-es6-prefix-dependency.js, src/goog-loader-es6-suffix-dependency.js, src/goog-require-parser-plugin.js, src/index.js
Add support for goog.module.declareNamespace at runtime. 
TODO to make the dependency ordering correct.
=> Add support for goog.module.declareNamespace at runtime

demo/mixed-modules/package-lock.json, demo/mixed-modules/package.json
The demo contained out-of-date dependencies with known security vulnerabilities. Update them to address the findings.
=> Update the demo dependencies to address security vulnerabilities

demo/mixed-modules/package-lock.json, demo/mixed-modules/package.json, demo/mixed-modules/src/app.js, demo/mixed-modules/src/lib/esModule.js, demo/mixed-modules/src/lib/forwardEsModule.js
TODO to use the updated name of goog.declareModuleId, which requires a new compile release.
=> feature: Sort dependencies with declareNamespace

src/index.js
=> feat: allow passing extra command args to java closure compiler

src/closure-compiler-plugin.js
Extends #99 
Handles both variations of the source map property
=> fix source_map reference

demo/mixed-modules/src/lib/es6-lazy.js, demo/mixed-modules/webpack.config.js, src/closure-compiler-plugin.js, src/dependencies/amd-define-dependency.js, src/dependencies/goog-dependency.js, src/dependencies/goog-loader-es6-prefix-dependency.js, src/dependencies/goog-loader-es6-suffix-dependency.js, src/dependencies/goog-loader-prefix-dependency.js, src/dependencies/goog-loader-suffix-dependency.js, src/dependencies/harmony-export-dependency.js, src/dependencies/harmony-import-dependency.js, src/dependencies/harmony-marker-dependency.js, src/dependencies/harmony-noop-template.js
Ensure that the hash functions change when the closure templates are applied
=> Update hash for overwritten templates

src/dependencies/goog-base-global.js
=> Ensure that the goog.global property references window in uncompiled mode

src/closure-compiler-plugin.js, src/common-ancestor.js
=> Reduce recursive calls to lessen heap usage

src/closure-compiler-plugin.js
=> Support chunkhash naming in entrypoints

demo/es5-and-es6/package-lock.json, demo/es5-and-es6/package.json, demo/mixed-modules/package-lock.json, demo/mixed-modules/package.json, package-lock.json, package.json, src/closure-compiler-plugin.js
=> fix: STRICT is undefined

src/dependencies/goog-dependency.js, src/goog-require-parser-plugin.js
=> fix: include goog.requireType in build dependencies

package-lock.json, package.json
=> Update dependencies to address security alerts

src/goog-require-parser-plugin.js
Update the acorn parse options to reflect the latest documentation.
=> Modernize acorn parse options

demo/es5-and-es6/package-lock.json, demo/es5-and-es6/package.json, demo/mixed-modules/package-lock.json, demo/mixed-modules/package.json
Update deps in demo projects to address security alerts
=> Update dependencies in demos
